import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/ui/nav";
import { JetBrains_Mono } from "next/font/google";
import Footer from "@/components/ui/footer";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Adjust weights as needed
  variable: "--font-jetbrains", // Custom CSS variable for use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cx = (...classes: string[]) => classes.filter(Boolean).join(" ");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark" // Always apply dark class
    >
      <body className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
        <main
          className={cx(
            "flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0",
            jetbrainsMono.className
          )}
        >
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
